name: Covert picture to .jxl format and upload to Github Release of this repository
'on':
  release:
    types:
      - published
jobs:
  build:
    runs-on: macos-13
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      
      - name: Install jpeg-xl
        run: |
          brew install jpeg-xl

      - name: Build archive
        shell: bash
        run: >
          staging="jxl_file-${{ github.event.release.tag_name }}

          mkdir "$staging"

          cjxl img/view.jpg view.jxl

          cp {img/view.jpg,view.jxl} "$staging/"

          tar czf "$staging.tar.gz" -C "$staging" .

          echo "ASSET=$staging.tar.gz" >> $GITHUB_ENV
          
      - name: Upload release archive
        uses: actions/upload-release-asset@e8f9f06c4b078e705bd2ea027f0926603fc9b4d5
        env:
          GITHUB_TOKEN: '${{ secrets.WITH_GITHUB_TOKEN }}'
        with:
          upload_url: '${{ github.event.release.upload_url }}'
          asset_path: '${{ env.ASSET }}'
          asset_name: '${{ env.ASSET }}'
          asset_content_type: application/octet-stream
